#include "pch.h"
#include"BookTest.h"
#include"CourseTest.h"
#include"DepartmentTest.h"
#include"EnrollmentTest.h"
#include"ExamTest.h"
#include"FeedbackTest.h"
#include"GradeTest.h"
#include"HumanTest.h"
#include"LibraryTest.h"
#include"LoanTest.h"
#include"NotificationTest.h"
#include"ScheduleTest.h"
#include"SkipsTest.h"
#include"StudentTest.h"
#include"TeacherTest.h"
